jobs:
  - name: nginx-manifest-1
    type: manifest
    steps:
      - IN: nginx-image

  - name: runSh-Job
    type: runSh
    steps:
      - IN: sample_java_ciRepo
      - IN: nginx-manifest-1
      - TASK:
        - script: sudo apt-get install tree
        - script: tree -F IN
        - script: sleep 3
    on_success:
      - script: echo "successfully completed"

  - name: sample_pipelines_runCI
    type: runCI
    steps:
      - OUT: nginx-image

  - name: sample_java_runCI
    type: runCI
    steps:
      - IN: nginx-manifest-1

  - name: validate_gitRepo_runSh
    type: runSh
    steps:
      - IN: sample_java_gitRepo
      - TASK:
        - script: sudo apt-get install tree
        - script: tree -F IN
        - script: sleep 3
    on_success:
      - script: echo "successfully completed"
