jobs:
  - name: nginx-manifest-new
    type: manifest
    steps:
      - IN: nginx-image-new
      - TASK: managed

  - name: ddc-deploy-new
    type: deploy
    steps:
      - IN: nginx-manifest-new
      - IN: ddc-cluster-new
      - TASK: managed
