jobs:
  - name: ubuntu-hello-world
      type: runSh
      runtime:
        architecture: x86_64
        os: Ubuntu_16.04
        container: false
      steps:
        - TASK:
            name: test-hello-world
            script:
              - echo "hello world guys !!!"
