jobs: 
  - name: manifest-0a
    type: manifest
    steps:
      - IN: nginx-image-10
    flags:
      - flag-1

  - name: manifest-1a
    type: manifest
    steps:
      - IN: manifest-0a
    flags:
      - flag-1
  
  - name: manifest-2a
    type: manifest
    steps:
      - IN: manifest-1a
    flags:
      - flag-2
      
  - name: manifest-1b
    type: manifest
    steps:
      - IN: nginx-image-10
    flags:
      - flag-3
      
  - name: manifest-2b
    type: manifest
    steps:
      - IN: manifest-1b
    flags:
      - flag-4
  
  - name: manifest-1c
    type: manifest
    steps:
      - IN: nginx-image-10
    flags:
      - flag-5
      
  - name: manifest-2c
    type: manifest
    steps:
      - IN: manifest-1c
    flags:
      - flag-6   
 
  - name: manifest-1d
    type: manifest
    steps:
      - IN: nginx-image-10
    flags:
      - flag-7
  
  - name: manifest-2d
    type: manifest
    steps:
      - IN: manifest-1d
    flags:
      - flag-8
